### ISSUE TITLE
a copy function that can copy all results

### ISSUE THREAD

**Issue by WillCGitHub** [WillCGitHub/PN-MOSFET-Calculator#2]
I'm considering to add in a copy function that can copy all the results as a dictionary type data. 

For example,
when paste, one can get 
{'Built-in Potential': '0.6V', 'Capacitance':'8.31 nF' }

**Comment by Dai0526** [comment]
I don't completely understand your idea.
Is that means once I enter the data for n-mode, if I click "copy", the data fields in p-mode calculator will be filled automatically?

**Comment by WillCGitHub** [comment]
I may not express myself clearly. 
What I mean is the following:
After pressing calculate button, the RESULT area will show the results. If someone tries to get the result, he has to copy and paste each text field. Presumably, if there is a copy button, the user can get all data into his copy board by clicking the copy button once. After he pasting the result into somewhere, the result will show up like a dictionary type data {'Built-in Potential': '0.6V', 'Capacitance':'8.31 nF' }

**Comment by WillCGitHub** [comment]
fix
